### ISSUE TITLE
hop.inria.fr est inaccessible

### ISSUE THREAD

**Issue by hugues-koolsol** [manuel-serrano/hop#107]
Bonjour
http://hop.inria.fr/ est inaccessible.
Serait-il possible d'y avoir accès ou à d'avoir accès à un site équivalent
D'avance, je vous remercie
Bonne journée
Hugues

**Comment by manuel-serrano** [comment]
Thanks for your message. I have no idea why http://hop.inria.fr was no longer reachable. It is now up again. 

Sorry for the inconvenience.

**Comment by hugues-koolsol** [comment]
Merci

**Comment by hugues-koolsol** [comment]
Impressionnant !
Pour information, il y a 2 pages manquantes dans la rubrique api :
http://hop.inria.fr/home/hz.html
http://hop.inria.fr/home/exif.html
Hugues
PS : pour votre information, je suis allé voir hop car j'ai vu votre présentation sur les vidéos du collège de France

**Comment by FlorianBELLAZOUZ** [comment]
Bonjour @manuel-serrano 

Le site est à nouveau inaccessible.

http://hop.inria.fr/
