### ISSUE TITLE
try-catch blocks on websocket initialization does not work properly 

### ISSUE THREAD

**Issue by klpanagi** [manuel-serrano/hop#26]
Following the latest commits, websocket initiation does not throw an Exception on failure anymore.
For example if the websocket end-point does not exist.

```js
var wsEndPoint = 'ws://localhost:9090'
try { ws = new Websocket( wsEndPoint ) }
catch(e) { console.log(e) }
```
The catch block does never get any Exceptions...

This seems to be an issue since parent commit:  09f4a19e7928c547fe86402284ee5b0be6f2e9df

**Comment by manuel-serrano** [comment]
This is because opening the websocket is asynchronous. Use the following instead:

    var wsEndPoint = 'ws://localhost:9090'
    try {
       ws = new WebSocket( wsEndPoint )
       ws.onerror = function( e ) {
          console.error( e.value );
      }
  }
