### ISSUE TITLE
Failure during the installation

### ISSUE THREAD

**Issue by xvw** [manuel-serrano/hop#34]
Hi, after the presentation at OSIS2016, I have try to install Hop.JS on my machine (Mac osx El Capitan). 
I have installed all prerequesite : 

autoconf
automake
curl
gawk
getopt (known as gnu-getopt on Brew)
giflib
gmp
libtool
libunistring
pcre
openssl
sqlite3
And Bigloo. 

I run "./configure"
and "make" but i have this error : 

```

File "process.scm", line 673, character 22151:
#		  (ioctl (inexact->exact (js-tointeger fd %this))
#		  ^
*** ERROR:<anonymous:1958>
Unbound variable -- ioctl
1 error occured, ending ...
make[2]: *** [o/process.o] Error 255
make[1]: *** [build] Error 2
make: *** [nodejs] Error 2
```

Thanks a lot for your feedback.

**Comment by vprunet** [comment]
Hi Xavier,

Ioctl was added recently to bigloo and is not available on bigloo releases older than a few weeks.
You should check that ioctl in available in the version of bigloo used in building your hop.js.

sarasvati:~ vprunet$ bigloo
------------------------------------------------------------------------------
Bigloo (4.3a)                                                            ,--^, 
`a practical Scheme compiler'                                      _ ___/ /|/  
Thu Jun 2 09:13:26 CEST 2016                                   ,;'( )__, ) '   
Inria -- Sophia Antipolis                                     ;;  //   L__.    
email: bigloo@lists-sop.inria.fr                              '   \    /  '    
url: http://www-sop.inria.fr/indes/fp/Bigloo                       ^   ^       
------------------------------------------------------------------------------


1:=> ioctl;
#<procedure:10f28a260.-3>
1:=> 

If ioctl is not defined, please install a recent version of bigloo. The following one, or a more recent one, should be ok.
ftp://ftp-sop.inria.fr/indes/fp/Bigloo/bigloo4.3a-alpha04Jun16.tar.gz

Vincent

**Comment by xvw** [comment]
Thanks a lot, after bigloo's news version installation, I have this error : 
```
ld: warning: -read_only_relocs cannot be used with x86_64
Undefined symbols for architecture x86_64:
  "_make_extended_pair", referenced from:
      _BGl_ignorez72z72zz__hop_readz00 in read.o
      _BGl_ignorez00zz__hop_readz00 in read.o
      _BGl_collectzd2uptozd2zz__hop_readz00 in read.o
      _BGl_readzd2quotezd2zz__hop_readz00 in read.o
      _BGl_definezd2tagzd2zz__hop_expandersz00 in expanders.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [shared-install-name] Error 1
make[4]: *** [shared] Error 1
make[3]: *** [shared-lib] Error 1
make[2]: *** [/Users/xvw/Packages/hop/lib/hop/3.0.0/libhop_s-3.0.0.dylib] Error 2
make[1]: *** [lib-c-shared] Error 2
make: *** [lib] Error 2
```

I have take hop from this repo (via git clone)

**Comment by vprunet** [comment]
Several persons in our team, including me, are also on OSX El Capitan, using the latest hop.js
https://github.com/manuel-serrano/hop/commit/445848e4000f6319dcc055971e115435d3fe736e, 
and bigloo4.3a-alpha04Jun16.tar.gz with no issue.
I suspect an issue at configure time which prevents to find the proper bigloo libraries.

Can you try to
- delete the installed bigloo by hand (in /usr/local or  $PREFIX directory )
- get a fresh bigloo build tree, compile and install ( untar, configure, make, make install)
- get a fresh hop build tree (cloning again from github master), in case make cleanall misses to delete some file
-configure, make, make install hop. Be sure to specify the right bigloo installation directory at configure time (default is to look for bigloo executable and tools in $PATH and for bigloo libraries in /usr/local)


If you are still out of luck, please send me these files:
bigloo/configure.log
hop/etc/Makefile.hopconfig

You may also check installed libraries with otool -L

**Comment by xvw** [comment]
Its seems worked ! Thanks ! 
(But when I try `make test` "make: `test' is up to date.")
