### ISSUE TITLE
Sending files to client without compiling

### ISSUE THREAD

**Issue by lphilips** [manuel-serrano/hop#37]
Hi,

I'm writing a small project with hop.js and I'd like to use a twitter bootstrap calendar library (https://github.com/Serhioromano/bootstrap-calendar).
The library requires some template files (under /tmpls) to be available on the client side. These template files are HTML files that contain some escape characters with JS code in there, so the HOP compiler complains e.g.:
`<% if(all_day.length) {%>` gives a ReferenceError: days_name is not defined.
This happens if I load all the necessary files by using the modules options in the HTML header.

Is there another way of sending files to the client side, for example by putting them in a public folder?

**Comment by vprunet** [comment]
Hi,
Here is an example of how you can send files (js and other resources) to the client without compilation on the server side.
[hop/examples/pdfviewer/pdfviewer.js](url)

Hope this helps,

Vincent

**Comment by lphilips** [comment]
Thank you for the quick answer!

Using XMLHttpRequest is indeed a good way to send the content of a file to the client.
However, what I want to achieve is to send the content of the file to the client and save it on the client side as well, not just injecting it into the current HTML page.

Basically the files I want to send are just like images or css files and need to be available in the project directory on the client side.
