### ISSUE TITLE
Using bigloo to detect errors in hop code?

### ISSUE THREAD

**Issue by svenha** [manuel-serrano/hop#42]
Hi.

Is there a simple way to compile hop files with bigloo only to detect some basic errors like unbound identifiers, incorrect argument counts etc. The idea is to use some dummy bindings to make bigloo happy with special hop constructs and to stop compilation at an early stage because we cannot use the resulting code anyway. Does such a tool or script exist?

Ciao
Sven

**Comment by manuel-serrano** [comment]
Hi Sven,

You can try hopc. For instance:

$ cat > foo.hop <<EOF
(module foo
   (export (foo x y)))

(define (foo x y)
   (bar x))

(define (bar a b)
   (string-append a b))
EOF
$ hopc foo.hop

File "foo.hop", line 5, character 57:
#   (bar x))
#   ^
*** ERROR:foo
Illegal application: 2 arg(s) expected, 1 provided -- (bar x)
1 error occured, ending ...

But this holds only for server side computations. It's much harder to
detect these sort of things inside client-side computations as the code
may change after each service call.

-- 
Manuel

**Comment by svenha** [comment]
Thanks. This helps a lot because server-side computations are the main part of my hop project.
