### ISSUE TITLE
Missing Job Queue for Promise Actions?

### ISSUE THREAD

**Issue by vprunet** [manuel-serrano/hop#47]
Hi,

We found that the hop.js resolution/rejection of promises synchronously triggers the registered actions, while other JavaScript implementations defer the execution.

The ECMA 262 specification of [performpromisethen](https://www.ecma-international.org/ecma-262/6.0/#sec-performpromisethen) states that the actions should be enqueued in a Job queue (see [EnqueueJob](https://www.ecma-international.org/ecma-262/6.0/#sec-enqueuejob)) .
Hop.js does not comply to the above section of the specification.

_test.js_
```js
var r;

var p = new Promise( function( resolve, reject ){
  r = resolve;
});

p.then(function() {
  console.log( 'In resolve action');
});

r();
console.log( 'End of script');
``` 

_bash_
```bash
$ hop test.js 
In resolve action
End of script
```

Vincent

**Comment by bigloo-dev** [comment]
Indeed. For a reason that I cannot remember, there is a macro defined
in the promise implementation that overrides the normal asynchronous
thunk enqueuing. Removing this macro should do be enough to fix that
problem...

**Comment by vprunet** [comment]
Merci!
