### ISSUE TITLE
Async functions and try/catch

### ISSUE THREAD

**Issue by cedricDum** [manuel-serrano/hop#48]
Hi,

I have a problem when I try to use the return statement inside a try/catch block and when the try/catch block is inside an async function. In this case, the return statement don't stop the function but it seems to throw an exception.
I put an example below

_test.js_

```js
async function get() {
  try {
    console.log( "Trying..." );
    let obj = { foo: "foo" };
    return obj;
  } catch( err ) {
    console.log( "catch error=", err );
    let obj = { bar: "bar" };
    return obj;
  }
}

( async function() {
  let obj = await get();
  console.log( "OBJ=", obj );
} ) ();
```

_bash_

```bash
$ hop --js-es6 --js-es2017 test.js
Trying...
catch error= 1
OBJ= { bar: 'bar' }
```

I'm using the latest hop (ca0db5e)

Best,
Cedric

**Comment by bigloo-dev** [comment]
Yes, this is an old problem in the CPS conversion. I have uploaded the fix. Thanks for your report.

**Comment by cedricDum** [comment]
Thank you, it's working fine
