### ISSUE TITLE
Class with hop 3.2

### ISSUE THREAD

**Issue by cedricDum** [manuel-serrano/hop#58]
Hi Manuel,

I have an issue with the class in hop 3.2. I can not create a function named `get` or `set` within a class. I put an example below

```javascript
class Animal {
  constructor(name) {
    this.name = name;
  }

  get() {
    return this.name;
  }

  set() {
    this.name = "john";
  }
}

let animal = new Animal("Jean");
console.log(animal.name);
console.log(animal.get());
animal.set();
console.log(animal.name);
```

```bash
$ hop-3.2.0 test-class.js

File "test-class.js", line 6, character 69:
#  get() {
#     ^
*** ERROR:hopscript
Wrong property name -- (
    1. &pthread-1045,
```

Thanks you,
Cedric

**Comment by manuel-serrano** [comment]
Oh yes! I see the problem. JavaScript syntax is really more and more ambiguous as "get" is a keyword
to introduce properties as in:

function kangaxi() {
   var baz = false;
   class C {
      get foo() { return "foo"; }
      set bar(x) { baz = x; }
   }
   new C().bar = true;
   return new C().foo === "foo" && baz;
}

but it can also be used as a plain identifier as in your example.

I have fixed the parser accordingly. I'm currently running the test (it now takes a while). As soon as the
tests are passed, I will upload a new version.

Once again, thanks for your testing and for having drawn my attention to this problem.

--
Manuel
