### ISSUE TITLE
How to hide hop's config files?

### ISSUE THREAD

**Issue by svenha** [manuel-serrano/hop#67]
I am running hop in a chroot. Inside the chroot, the directory .config/hop must be available for the hop binary to start. But how can I prevent files from .config/hop to be read by anonymous users? My `anonymous` user is defined as:

    (add-user! "anonymous" :directories (list "/hop" "/static") :services (quote (demo)))

**Comment by manuel-serrano** [comment]
Hop grants access to the directories (hop-share-directory) and (hop-var-directory). By default
(hop-var-directory) is $HOME/.config/hop. You can change that by setting its value in your hoprc.hop
file, for instance:

  (hop-var-directory-set! "/tmp/var")

Please let me know if this fixes your problem.

**Comment by svenha** [comment]
Yes, this would be a solution. But I would prefer a fix that is more secure even for the standard setup that hop's wizard generates.
