### ISSUE TITLE
Wizard broken in hop 3.3

### ISSUE THREAD

**Issue by svenha** [manuel-serrano/hop#73]
The wizard writes an incorrect file because `hop` reports the following error:

    File ".config/hop/hoprc.hop", line 9, character 261:
    #(hop-http-authentication (quote basic))
    #^
    *** ERROR:eval
    Wrong number of arguments: 0 expected, 1 provided  -- hop-http-authentication
    1. eval, .config/hop/hoprc.hop:9

Workaround: comment out this line 9. Or something else?

**Comment by svenha** [comment]
@manuel-serrano This problem still exists and should be fixed in the planned release IMHO. It is now (3.3.0-pre1 from 2020-03-27) complicated by the fact that the line number reported seems to ignore comment and empty lines. So in my case, it reports line 3.

**Comment by manuel-serrano** [comment]
Thanks for the report. The error is now fixed.
