### ISSUE TITLE
 `make` doesn't succeed on Ubuntu 18

### ISSUE THREAD

**Issue by vidjuheffex** [manuel-serrano/hop#75]
init.scm fails due to:
Unbound variable -- seconds->gmtdate

**Comment by vidjuheffex** [comment]
changed the call to seconds->date (looked through the history of init.scm to see what had maybe changed around that line)

**Comment by manuel-serrano** [comment]
The change seconds->date to seconds->gmtdate was needed to comply with the HTTP protocol. Older Hop version reply a last-modified header in a non-gmt time, which is illegal. The function seconds->gmtdate is implemented in Bigloo. This is why the version 4.3h is needed to compile the last Hop version.

Hopefuly all these problems witll be fixed soon..

**Comment by vidjuheffex** [comment]
Oh I see, the bigloo site has only 4.3g, and the 4.3h download link on hop is a broken link, FYI. Thanks!
