### ISSUE TITLE
markdown.loadDocument is undefined

### ISSUE THREAD

**Issue by vidjuheffex** [manuel-serrano/hop#76]
markdown.load is present, but attempting to use markdown.loadDocument kept giving me a "error in call1: not a function"

So I console logged markdown.loadDocument and found that in fact that was undefined.

**Comment by vidjuheffex** [comment]
maybe I'm fundamentally misunderstanding the markdown support? 

I've tried using `load` and using the `.XML` property but that doesn't return XML as I expected, instead it returns:

```
((new sc_Pair(hop_create_encoded_element("%3Ch1%20id%3D%27g1137%27%20class%3D%27toc%20markdown%20%27%3EHello%20World%3C/h1%3E"),(new sc_Pair(hop_create_encoded_element("%3Cp%20id%3D%27G0%27%20class%3D%27markdown%20%27%3EThis%20is%20a%20test%20blog%20post%0A%3C/p%3E"),null)))))
```

so I tried using `eval` after ensuring I could get the document as a string using `fs`:

```
postFilenames.forEach(filename => {
  const filepath = postDir + "/" + filename;
  const svc = new hop.Service(() => {
    return <md.markdown>${fs.readFileSync(postDir + "/" + filename, 'utf8')}</md.markdown>
  })
  svc.path = "/hop/my-test";
})
``

However this returns the same result as above.

**Comment by manuel-serrano** [comment]
You have understood correctly and you have just found a bug. The method loadDocument was
bound internally but not exported as it should have been by the hop.markdown module. You can now use it as follows:

```javascript
const md = require( hop.markdown );
service foo() {
   return <HTML>
     ${ md.loadDocument( require.resolve( "./foo.md" ) ) }
   </HTML>
}
```

foo.md
```markdown
TItle
====

  * A
  * B
```
