### ISSUE TITLE
small syntax error in wizard generated JS

### ISSUE THREAD

**Issue by bonthron** [manuel-serrano/hop#82]
There's a small bug in the wizard, when the guest user was created, the object passed to user.add()  was missing the closing curly brace } 

// guest
user.add( { name: 'guest', 
            groups: [ 'guest' ],
            password: '*****************',
            directories: ['/home/jason/.config/hop/guest', '/tmp', '/home/jason/.config/hop/cache/9cf1dd678', '.', '/home/jason/.config/hop', '/opt/hop/share/hop/'+ hop.version, '/opt/hop/lib/hop/'+ hop.version+ '/weblets', '/opt/hop/share/hop/contribs'] **}** )

**Comment by manuel-serrano** [comment]
Dear Jason,

You are right. This was a bug in the wizard.js code generation. Hopefully, thanks to your report I have been able to fix it.
