### ISSUE TITLE
script tag should not specify JavaScript

### ISSUE THREAD

**Issue by svenha** [manuel-serrano/hop#84]
When I validate pages generated by Hop, I get many warnings like this:

    The type attribute is unnecessary for JavaScript resources.
    From line 10, column 233; to line 10, column 272
    <script type='application/x-javascript'>

To avoid them and to save some bandwidth, can Hop suppress the type attribute in such cases?

**Comment by manuel-serrano** [comment]
You are correct. I have fixed that for the yet to be released version 3.5.0.
