### ISSUE TITLE
configure problem with gmp.h on macos

### ISSUE THREAD

**Issue by bentxt** [manuel-serrano/hop#86]
hi,
I try to install hop on latest macos. Bigloo and gmp are installed with brew

```
./configure
In file included from /tmp/bigloo-test-hop.c:14:
In file included from /usr/local/Cellar/bigloo/4.4c-2/lib/bigloo/4.4c/bigloo.h:110:
/usr/local/Cellar/bigloo/4.4c-2/lib/bigloo/4.4c/bigloo_config.h:688:12: fatal error: 'gmp.h' file not found
#  include <gmp.h>
           ^~~~~~~
1 error generated.
```

```
$ head /usr/local/include/gmp.h
/* Definitions for GNU multiple precision functions.   -*- mode: c -*-
....
```
```

echo $PKG_CONFIG_PATH
/usr/local
echo $LIBRARY_PATH
/usr/local
```

**Comment by manuel-serrano** [comment]
Hi,

Thanks for your report.

it seems that /usr/local is not in the clang default include path. Maybe the solution is to use PKG_CONFIG_PATH or something similar. I'll investigate and come back to you when I have found the solution.

**Comment by manuel-serrano** [comment]
Hi, 

I have updated and uploaded a new Bigloo version that, as far as I can tell, fixes that problem.
Once again (http://www-sop.inria.fr/indes/fp/Bigloo/download/bigloo-latest.tar.gz). Once again, thanks for your report.

**Comment by bentxt** [comment]
Thank you for uploading a fixed bigloo version. I could install it and this particular error did no longer occur when building hop.
