### ISSUE TITLE
Clang errors when building hop on macos

### ISSUE THREAD

**Issue by bentxt** [manuel-serrano/hop#87]
I receive 2 errors when compiling hop on macos:

$ clang -v
```
Homebrew clang version 13.0.0
Target: x86_64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```

error log for  `make`: 

 65 /Applications/Xcode.app/Contents/Developer/usr/bin/make -C hopscript build
 66 ^[[0m^[[1;30mgcc^[[0m -O -I/usr/local/include -L/usr/local/lib -I/usr/local/include -fbracket-depth=1024 -Wno-unused-value -    Wno-parentheses-equality -Wno-parentheses -Wno-invalid-source-encoding -Wno-return-type -Wno-trigraphs -I/usr/local/lib/bigl    oo/4.4c -fPIC -DBGL_NAN_TAGGING=0    -c _bglhopscript.c -o o/_bglhopscript.o  ^[[0m^[[1;31m^[[0m
 67 clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
 68 _bglhopscript.c:904:11: error: implicit declaration of function 'bgl_make_jsobject_sans' is invalid in C99 [-Werror,-Wimplic    it-function-declaration]
 69    return bgl_make_jsobject_sans((int)constrsize, constrmap, __proto__, mode);
 70           ^
 71 _bglhopscript.c:904:11: note: did you mean 'bgl_make_jsobject_bmem'?
 72 _bglhopscript.c:903:1: note: 'bgl_make_jsobject_bmem' declared here
 73 bgl_make_jsobject_bmem(int constrsize, obj_t constrmap, obj_t __proto__, uint32_t mode) {
 74 ^
 75 _bglhopscript.c:904:11: warning: incompatible integer to pointer conversion returning 'int' from a function with result type     'obj_t' (aka 'union scmobj *') [-Wint-conversion]
 76    return bgl_make_jsobject_sans((int)constrsize, constrmap, __proto__, mode);
 77           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 78 _bglhopscript.c:1401:11: error: implicit declaration of function 'bgl_make_jsprocedure_sans' is invalid in C99 [-Werror,-Wim    plicit-function-declaration]
 79    return bgl_make_jsprocedure_sans(procedure, arity, __proto__);
 80           ^
 81 _bglhopscript.c:1401:11: note: did you mean 'bgl_make_jsprocedure_bmem'?
 82 _bglhopscript.c:1400:1: note: 'bgl_make_jsprocedure_bmem' declared here
 83 bgl_make_jsprocedure_bmem(obj_t procedure, long arity, obj_t __proto__) {

**Comment by manuel-serrano** [comment]
Did you get that error from the "master" branch or from the "3.5.x" branch? I realize that this issue has been fixed on 3.5.x
(at least, to the best of my knowledge) but that I have forgotten to merge that fix on the master branch...

I hope to release 3.5.x next week, I just need to complete the implementation of one minor feature and do some testing.

**Comment by bentxt** [comment]
yes it was using the master branch. 
now that you mention 3.5.x, I did try that and it built hop successfully.

**Comment by manuel-serrano** [comment]
Ah good. I feel relieved :-) (I have propagated the fix onto the master branch.)

**Comment by bentxt** [comment]
thanks for your help
