### ISSUE TITLE
NaN write behavior in JSON.stringify method diverging from standards specifications

### ISSUE THREAD

**Issue by l-poirier** [manuel-serrano/hop#89]
Writing a NaN to a JSON file compiled with hopc diverges from what ECMAScript specifies.

### Code
```js
console.log(JSON.stringify({a: NaN}))
```

(Built and executed with `hopc example.js; ./a.out`)

### Current behavior

Prints `{"a":+nan.0}` in console.

### Expected behavior

Should print `{"a":null}` in console since :
* `NaN` is not finite : _"boolean isFinite() [...] (not infinite or NaN)"_ [\[IEEE-754 5.7.2, 2019\]](https://doi.org/10.1109/IEEESTD.2019.8766229)
* `null` should be returned for non finite numbers : _"If value is finite return ! [ToString](https://262.ecma-international.org/#sec-tostring)(value). else return "null" "_ [\[ECMAScript 25.5.2.1.9.a, 2021\]](https://262.ecma-international.org/#sec-serializejsonproperty)

**Comment by manuel-serrano** [comment]
Hi Lucien,

Thanks for the report. I have fixed it. It was an easy one. A minor problem of pretty-printing.
