### ISSUE TITLE
Penalize IPs causing many 401 errors

### ISSUE THREAD

**Issue by svenha** [manuel-serrano/hop#90]
Can Hop penalize IPs that cause many 401 errors? By slowing down or blocking or ...?

**Comment by manuel-serrano** [comment]
There is no hook to interpose before a 401 reply however, as authentication responses are handled using a dedicated response class, the following should work:

```
(module hop-example)

(define-method (http-response r::http-response-authentication request socket)
   (print "request client authentication " request)
   (call-next-method))

(define-service (foo)
   (<HTML> "yep"))

```

**Comment by svenha** [comment]
Sorry, I don't understand the solution. I added just the define-method from above to my hop 3.5.0 program. But I don't see any print outs ("request client authentication) in the logs.

**Comment by svenha** [comment]
OK. Over time, I have collected some log messages. I guess that my code must decide which requests are valid and the code cannot access the HTTP error code (because it will determined later)?

**Comment by svenha** [comment]
I will try another approach. I analyze Hop's access log and feed top violators (from the last N days) into my existing list of blocked or delayed IPs.
